### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by GriffinMartin** [GriffinMartin/MI-449-SS17-740-js-serving-content-with-express-OctGcX#1]
@egillespie Can you take a look at this? It's [hosted here](https://mart1444-kfxl35erbteu5octgcx.herokuapp.com/) and meets the following criteria:

- [x] No code is repeated in your files; create a partial for any shared elements (`nav`, `head`, `header`, etc.)
- [x] Make a navigation to move throughout your site, using `forEach` to create a set of links to other data pages
- [x] Each item should have an object with an image, a link, a title, and more properties based on your topic (i.e. sandwich ingredients, movie release date, etc.)
- [x] Include at least 3 data pages and a homepage; routes should be created in Express for each
- [x] Use data appropriately with HTML tags (paragraphs in `p` tags, headings in `h1`-`h6`, etc.)
- [x] Use `express.static` to create a folder for static assets (images, stylesheets, etc.)
- [x] Include a `.gitignore` file so that `node_modules` and any other unnecessary files are not commited to github

**Comment by egillespie** [comment]
Hi @GriffinMartin, this is a solid start and it looks like you've got the gist of the lesson, but there is some room for improvement. Here are my recommendations:

### Use legit HTML, JS, and CSS

Do you mind linting your CSS, JS, and HTML? Then make sure you're producing [completely valid HTML](https://validator.w3.org/check?uri=https%3A%2F%2Fmart1444-kfxl35erbteu5octgcx.herokuapp.com%2Fun&charset=%28detect+automatically%29&doctype=Inline&group=0)?

### Avoid names already in use in `package.json`

The `name` field in your `package.json` file should indicate the name of _your_ project. Since `express` has already been used, can you pick something else more specific to your project?

If you ever need to check whether a name is in use, you can do a search at [npmjs.com](https://www.npmjs.com/search?q=express).

### Replace `ef.ejs`, `sb.ejs`, and `un.ejs` with one template file

You can use `forEach` in `server.js` to loop over each of your pages and call `app.get`. By doing so, you can provide the URL for each route and pass the other data to a single template that can be reused to generate the HTML for all three of your pages. This is where the real power of a templating system beneifts developers because it saves you from rewriting (or copy-pasting) a lot of code.

### Remove `yarn.lock` from `.gitignore`

`yarn.lock` is an essential file that makes sure the versions of project dependencies that you are using on your computer are the ones that will be installed when I try to run this project on _my_ computer. Please remove`yarn.lock` from `.gitignore` and add it to your repository.

---

After you’ve made your changes and pushed them to GitHub and your hosted site, give it a once-over to make sure it looks right, then comment back here and I’ll take another look.

Thanks! 🤘

**Comment by GriffinMartin** [comment]
@egillespie I made the requested changes!
Let me know if there is any other refactoring I can do or code improvements ✨ 
Thanks!

**Comment by egillespie** [comment]
Now you're cooking with fire! 🔥 🚒 

Your templates and JavaScript look great now. I do have some recommendations for your `package.json` though:

### Move linters to `devDependencies`

In a production environment like Heroku, you typically don't want your dev dependencies to be installed because it adds extra time and makes your project take up more space.

I recommend moving your linters to `devDependencies` in `package.json` to avoid this and build a good habit. I also see that `standard` is not listed as a dependency. Please add that.

It looks like you include `stylelint` as a dependency, but are not using it. I recommend adding a script to call `stylelint` as part of your build.

### Add `yarn.lock`

After you've updated all of your dependencies, remove your `node_modules` directory and run `yarn install`. This will generate or update your `yarn.lock` file. Add this file to your repository and push it to GitHub. This will ensure that I am using the exact same versions of the dependencies as you.

---

After you’ve made your changes and pushed them to GitHub and your hosted site, give it a once-over to make sure it looks right, then comment back here and I’ll take another look.

Thanks! ⛵️

**Comment by GriffinMartin** [comment]
@egillespie Thanks for the feedback. 
I updated the JSON file. I was confused about dev vs dependencies but I get it now. 😃

**Comment by egillespie** [comment]
Glad to hear. This looks great, thanks! :shipit:
